name: Build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Setup JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 17
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache build deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/wrapper
            ~/.konan/cache
            ~/.konan/dependencies
          key: build-deps-${{ runner.os }}-${{ hashFiles('gradle/**', 'gradlew*', 'gradle.properties', '*.gradle*') }}
      - name: Set up Xcode
        run: |
          ls /Applications/Xcode*
          swift --version
          sudo xcode-select --switch /Applications/Xcode_16.2.app/Contents/Developer
          gem install xcpretty
      - name: Set up Swift
        uses: swift-actions/setup-swift@v2.2.0
      - name: Build
        run: ./gradlew linkDebugFrameworkIosArm64 assembleDebug
      - name: Test
        run: ./gradlew testDebugUnitTest jvmTest iosSimulatorArm64Test lintDebug